# Generated by Django 4.0.5 on 2022-06-26 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='ABC123', max_length=50)),
                ('password', models.CharField(default='12345678', max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('name', models.CharField(default='User', max_length=50)),
            ],
        ),
    ]
